server:
  applicationConnectors:
    - type: http
      port: 9080
  adminConnectors:
    - type: http
      port: 9081

database:
  driverClass: org.h2.Driver
  url: jdbc:h2:mem:notebooks;DB_CLOSE_DELAY=-1
  user: sa
  password: ""
  properties:
    hibernate.dialect: org.hibernate.dialect.H2Dialect
    hibernate.hbm2ddl.auto: create
    hibernate.show_sql: false

logging:
  level: INFO
  appenders:
    - type: console
